src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wcbn_core.urls')),
    path('', include('wcbn_auth.urls')),
    path('', include('wcbn_cms.urls')),
    path('', include('readback.urls')),
    path('', include('trix.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

src/wcbn_core/urls.py
from django.urls import path
from wcbn_core.views import *

app_name = 'wcbn_core'
urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),
]

src/wcbn_core/views.py
import requests
from django.views.generic import ListView
from wcbn_cms.models import Article
from django.conf import settings
from wcbn_cms.views import ArticleListView

def get_on_air():
    url = f'{settings.READBACK_URL}/playlist.json'
    resp = requests.get(url)
    return resp.json()


class HomepageView(ArticleListView):

    def get_context_data(self, **kwargs):
        ctx = super(HomepageView, self).get_context_data(**kwargs)
        ctx['title'] = 'Homepage'
        ctx['STUDIO_LINE'] = settings.STUDIO_LINE
        ctx['RESOURCE_LINKS'] = settings.RESOURCE_LINKS
        ctx['on_air'] = get_on_air()['on_air'] if 'prod' in settings.DJANGO_SETTINGS_MODULE else {}
        ctx['main'] = "articles/list.html"
        ctx['aside'] = "homepage/aside.html"
        ctx['IOS_URL'] = settings.IOS_URL
        ctx['ANDROID_URL'] = settings.ANDROID_URL
        return ctx

src/wcbn_core/templates/layouts/application.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  {% include "./head.html" %}
  <body>
    {% include "./header.html" %}
    {% include "../player.html" %}
    {% include "./messages.html" %}
    <div class="container px-4 m-auto flex-grow">
    {% block content %}{% endblock %}
    </div>
    {% include "./footer.html" %}
  </body>
</html>

src/wcbn_core/templates/layouts/footer.html
{% load ionicon %}
<footer>
<div id="footer-content" class="container">
  <div>
    <p>© 1972 - {% now "Y" %} WCBN</p>
  </div>

  <div id="social-media">
  {% for icon, url in SOCIAL_ICONS.items %}
  <a href="{{url}}" target="_blank" rel="noopener noreferrer">
    {% ionicon name=icon %}
    <p>{{icon}}</p>
  </a>
  {% endfor %}
  </div>
</div>
</footer>

src/wcbn_core/templates/layouts/head.html
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-itunes-app" content="app-id=600658964">
  {% if SHOULD_RELOAD %}
  <meta name="turbolinks-visit-control" content="reload">
  {% endif %}
  <title>{% if title %}{{title}} · {% endif %}WCBN</title>
  <link rel="shortcut icon" type="image/png" href='{% static "img/favicon.ico" %}' />

  <script defer src='{% static "dist/index.bundle.js" %}'></script>
  <script defer src='{% static "dist/stream.bundle.js" %}'></script>
  
  {% if ENV == "app.environments.development" %}
  <script src='{% static "dist/styles.bundle.js" %}'></script>
  {% else %}
  <link rel="stylesheet" type="text/css" href="{% static 'dist/styles.css' %}" />
  {% endif %}

  {% if GA_MEASUREMENT_ID %}
  <script async src="https://www.googletagmanager.com/gtag/js?id={{ GA_MEASUREMENT_ID }}"></script>
  <script> window.subscribeGTAG("{{ GA_MEASUREMENT_ID }}")</script>
  {% endif %}
</head>

src/wcbn_core/templates/layouts/header.html
{% load static %}
{% with view_name=request.resolver_match.view_name %}
<header>

  <nav class="container">

    <div id="wcbn-logo-wrapper">
      <a id="wcbn-logo" href="{% url 'wcbn_core:homepage' %}">
        <img src='{% static "img/logo.png" %}' alt="WCBN Logo" />
      </a>
    </div>
  
    
    <input id="nav-toggle-input" type="checkbox" />
    <label id="nav-toggle-label" for="nav-toggle-input"><span id="nav-toggle-icon"></span></label>

    <div id="nav-options">
      
      <ul class="nav-links-wrapper">
      {% for txt, href in NAV_TABS.items %}<li {% if view_name == href %}class="active"{% endif %}>
        <a href="{% url href %}">
          {{txt}}
        </a>
      </li>{% endfor %}
      </ul>

      <div class="flex-grow"></div>

      <ul class="nav-links-wrapper">
        {% if user.is_staff %}
        <li><a href="{% url 'admin:index' %}">Admin</a>
        </li>{% endif %}{% if user.is_authenticated %}<li>
        <a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        {% for txt, href in USER_NAV_TABS.items %}<li class="{% if view_name == href %}active{% endif %}">
          <a href="{% url href %}">{{txt}}</a>
        </li>{% endfor %}
        {% endif %}
      </ul>

    </div>
  </nav>
</header>
{% endwith %}

src/wcbn_core/templates/layouts/main_with_aside.html
{% extends "layouts/application.html" %}

{% block content%}
<div id="main-with-aside">
  <main>{% include main %}</main>
  <aside>{% include aside %}</aside>
</div>
{% endblock %}

src/wcbn_core/templates/layouts/messages.html
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
  <p class="container">{{ message }}</p>
  </li>
  {% endfor %}
</ul>
{% endif %}